#! usr/bin/env python

import sys
sys.stdin.readline()

for line in sys.stdin:
    line = line.strip()
    column = line.split(',')

    print("{0}\t{1}\t{2}".format(column[0], column[5], column[1]))



# usr/bin/env python

import sys
current_country = None
min_temp = None
min_city = None

for line in sys.stdin:
    line.strip()
    country, tempr, city = line.split('\t')

    if current_country == None:
        current_country = country
        min_temp = tempr
        min_city = city

    elif current_country == country:
        try:
            if float(tempr) < float(min_temp):
                min_temp = tempr
                min_city = city
        except ValueError:
            continue
    
    else:
        print("{0}\t{1}\t{2}".format(current_country, min_temp, min_city))
        current_country = country
        min_temp = tempr
        min_city = city

if current_country:
    print("{0}\t{1}\t{2}".format(current_country, min_temp, min_city))

    
































#! usr/bin/env python

import sys
import datetime
from datetime import datetime
sys.stdin.readline()

for line in sys.stdin:
    line = line.strip()
    data = line.split(',')
    price = (float(data[1]) + float(data[4])) / 2

    date_str = data[0]
    date = datetime.strptime(date_str, '%Y-%m-%d')
    year_month = date.strftime('%Y.%m')

    print("{0}\t{1}".format(year_month, price))




#! usr/bin/env python

import sys

current_date = None
total_sum = 0
count = 0

for line in sys.stdin:
    line = line.strip()
    date, price = line.split('\t', 1)

    try:
        price = float(price)
    except ValueError:
        continue

    if current_date == date:
        total_sum += price
        count += 1
    else: 
        if current_date:
            average_price = total_sum / count
            print("{0}\t{1}".format(current_date, average_price))
        current_date = date
        total_sum = price
        count = 1

if current_date:
    average_price = total_sum / count
    print("{0}\t{1}".format(current_date, average_price))






















#! usr/bin/env python
import sys

for line in sys.stdin:
    line = line.strip()
    words = line.split()

    for word in words:
        print("{0}\t{1}".format(word,1))


#! usr/bin/env python

from operator import itemgetter
import sys

current_word = None
current_count = 0
word = None

for line in sys.stdin:
    line=line.strip()
    word, count = line.split('\t')

    try:
        count = int(count)
    except ValueError:
        continue

    if current_word == word:
        current_count += count
    else:
        if current_word:
            print("{0}\t{1}".format(current_word,current_count))
        current_count = count
        current_word = word

if current_word == word:
    print("{0}\t{1}".format(current_word,current_count))



